### ISSUE TITLE
Colors look... off?

### ISSUE THREAD

**Issue by pocco81** [catppuccin/duckduckgo#3]
Here is what it looks like on my end:

![image](https://user-images.githubusercontent.com/58336662/152077773-b637237a-695d-4ba4-a90e-db3aca3f4dc1.png)

After using a color picker I found out that the background color is `#181821`. As you may know the main background is `black2` (`#1E1E2E`).

**Comment by esdmr** [comment]
oh. I forgot to check if the previous PR had the correct colors before submitting a new one.

I will try to fix it today.
