### ISSUE TITLE
No styles after applying the theme throught the bookmarklet?

### ISSUE THREAD

**Issue by sophiiss** [catppuccin/duckduckgo#6]
![image](https://user-images.githubusercontent.com/59633047/183306770-be0bec29-9808-48eb-8ebe-f3eaff427f83.png)

Steps:
Create the bookmarklet and run it on the ddg site.

**Comment by sophiiss** [comment]
Reloading the page with CTRL + SHIFT + R or CTRL + F5 fixes it.

**Comment by nekowinston** [comment]
I have documented the hard-reload, and also added doc for the script installation method. Please close if this looks good to you. 🙂 

P.S.: I will get to the Tailwind update soon, apologies for the wait on that.

**Comment by sophiiss** [comment]
Thank you!

Also, don't worry about it! Take your time.
