### ISSUE TITLE
Toggle between variations more easily

### ISSUE THREAD

**Issue by andreiborisov** [catppuccin/duckduckgo#7]
I have different Catppuccin variations activated throughout the day, while for most applications it's pretty easy to achieve, in the case of the DuckDuckGo theme it's not.

**Comment by nekowinston** [comment]
hi there 👋 

that would probably require making a usercss, since DDG's native way of handling themes is quite limited.

i'll look into it.

**Comment by andreiborisov** [comment]
It's nice they provide a native-theme mechanism, but if it's not a huge undertaken, UserCSS will also be great for more possible customizations in the future.

**Comment by MatthiasGrandl** [comment]
Yeah I use stylus for most my website styling needs as it offers the option to switch between styles based on system preferences. So I automatically switch between latte and mocha based on system light/dark preference.

**Comment by nekowinston** [comment]
New attempt [over here](https://github.com/catppuccin/userstyles/pull/486), this repo will get archived as soon as that PR is merged.
